include: package:lint/analysis_options_package.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
    # allow self-reference to deprecated members (we do this because otherwise we have
    # to annotate every member in every test, assert, etc, when we deprecate something)
    deprecated_member_use_from_same_package: ignore
    # Ignore analyzer hints for updating pubspecs when using Future or
    # Stream and not importing dart:async
    # Please see https://github.com/flutter/flutter/pull/24528 for details.
    sdk_version_async_exported_from_core: ignore


    # Don't put any logic in createState.
    # https://dart-lang.github.io/linter/lints/no_logic_in_create_state.html
    no_logic_in_create_state: true

    avoid_returning_null_for_future: warning
    prefer_void_to_null: warning
    always_require_non_null_named_parameters: warning
    avoid_init_to_null: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_returning_null: warning
    avoid_returning_null_for_void: warning
    null_closures: warning
    prefer_conditional_assignment: warning
    prefer_if_null_operators: warning
    prefer_null_aware_operators: warning
    unnecessary_null_aware_assignments: warning
    unnecessary_null_in_if_null_operators: warning
    use_if_null_to_convert_nulls_to_bools: warning


exclude:
  - "bin/cache/**"
  - "lib/generated/intl/messages_*.dart"
  # the following two are relative to the stocks example and the flutter package respectively
  # see https://github.com/dart-lang/sdk/issues/28463
  - "lib/i18n/messages_*.dart"
  - "lib/src/http/**"
  - "test_fixes/**"
  - "lib/generated/intl/**"

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #


    avoid_returning_null_for_future: true
    prefer_void_to_null: true
    always_require_non_null_named_parameters: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    null_closures: true
    prefer_conditional_assignment: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    prefer_null_aware_method_calls: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    use_if_null_to_convert_nulls_to_bools: true


    # Use parameter order as in json response
    # https://dart-lang.github.io/linter/lints/always_put_required_named_parameters_first.html
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    # https://dart-lang.github.io/linter/lints/avoid_classes_with_only_static_members.html
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    # https://dart-lang.github.io/linter/lints/sort_constructors_first.html
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: false
    prefer_double_quotes: false

    # Back to the 80s
    # https://dart-lang.github.io/linter/lints/lines_longer_than_80_chars.html
    lines_longer_than_80_chars: false

    # Prefer typing uninitialized variables and fields.
    # https://dart-lang.github.io/linter/lints/prefer_typing_uninitialized_variables.html
    prefer_typing_uninitialized_variables: true

    # Avoid using forEach with a function literal.
    # https://dart-lang.github.io/linter/lints/avoid_function_literals_in_foreach_calls.html
    avoid_function_literals_in_foreach_calls: true

    # Avoid setters without getters.
    # https://dart-lang.github.io/linter/lints/avoid_setters_without_getters.html
    avoid_setters_without_getters: true

    # Use Flutter TODO format: // TODO(username): message, https://URL-to-issue.
    # https://dart-lang.github.io/linter/lints/flutter_style_todos.html
    flutter_style_todos: true

    # Don't explicitly catch Error or types that implement it.
    # https://dart-lang.github.io/linter/lints/avoid_catching_errors.html
    avoid_catching_errors: false

    # Don't import implementation files from another package.
    # https://dart-lang.github.io/linter/lints/implementation_imports.html
    implementation_imports: true

    # Prefer asserts with message.
    # https://dart-lang.github.io/linter/lints/prefer_asserts_with_message.html
    prefer_asserts_with_message: true

    # Private field could be final.
    # https://dart-lang.github.io/linter/lints/prefer_final_fields.html
    prefer_final_fields: true
