name: take_home_assignment
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  audioplayers: ^4.0.1
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.5
  flutter_mobx: ^2.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  http: ^0.13.5
  intl: any
  json_annotation: ^4.8.0
  mobx: ^2.0.1
  path: ^1.8.2
  path_provider: ^2.0.2
  provider: ^6.0.4
  shared_preferences: ^2.0.6
  sqflite: ^2.2.0+3
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_svg: ^2.0.5
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mobx_codegen: ^2.0.1+3
  pubspec_dependency_sorter: ^1.0.3
  flutter_test: 
    sdk: flutter
flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true
flutter: 
  assets: 
    - assets/svg_icons/
    - assets/audio/
  fonts: 
    - 
      family: SFUIDisplay
      fonts: 
        - 
          asset: assets/fonts/Roboto/Roboto-Regular.ttf
          style: normal
          weight: 400
        - 
          asset: assets/fonts/Roboto/Roboto-Medium.ttf
          style: normal
          weight: 500
        - 
          asset: assets/fonts/Roboto/Roboto-Bold.ttf
          style: normal
          weight: 700
  uses-material-design: true
flutter_intl: 
  class_name: AppLocalizations
  enabled: true
